[2023-05-03T07:33:56.944+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.featuring_data_task_1 manual__2023-05-03T07:33:53.541330+00:00 [queued]>
[2023-05-03T07:33:56.965+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.featuring_data_task_1 manual__2023-05-03T07:33:53.541330+00:00 [queued]>
[2023-05-03T07:33:56.972+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T07:33:56.974+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-03T07:33:56.977+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T07:33:57.043+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): featuring_data_task_1> on 2023-05-03 07:33:53.541330+00:00
[2023-05-03T07:33:57.053+0000] {standard_task_runner.py:55} INFO - Started process 31493 to run task
[2023-05-03T07:33:57.082+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'featuring_data_task_1', 'manual__2023-05-03T07:33:53.541330+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp4iahkq8l']
[2023-05-03T07:33:57.083+0000] {standard_task_runner.py:83} INFO - Job 70: Subtask featuring_data_task_1
[2023-05-03T07:33:59.407+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.featuring_data_task_1 manual__2023-05-03T07:33:53.541330+00:00 [running]> on host 46ed3ffab080
[2023-05-03T07:33:59.645+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lequanghop844@gmail.com
AIRFLOW_CTX_DAG_OWNER=Felix Le
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=featuring_data_task_1
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T07:33:53.541330+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-03T07:33:53.541330+00:00
[2023-05-03T07:34:00.123+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/feature_engineering.py", line 20, in feature_engineering
    temp = list(map(adding_features,prefeaturing_list[batch_number]))
  File "/opt/airflow/dags/utils/features_added.py", line 13, in adding_features
    df = pd.read_parquet(file, engine='pyarrow')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 240, in read
    path_or_handle, columns=columns, **kwargs
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet/__init__.py", line 2793, in read_table
    thrift_container_size_limit=thrift_container_size_limit,
  File "/home/airflow/.local/lib/python3.7/site-packages/pyarrow/parquet/__init__.py", line 2368, in __init__
    [fragment], schema=schema or fragment.physical_schema,
  File "pyarrow/_dataset.pyx", line 898, in pyarrow._dataset.Fragment.physical_schema.__get__
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
[2023-05-03T07:34:00.152+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=featuring_data_task_1, execution_date=20230503T073353, start_date=20230503T073356, end_date=20230503T073400
[2023-05-03T07:34:00.238+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 70 for task featuring_data_task_1 (Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.; 31493)
[2023-05-03T07:34:00.403+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-03T07:34:00.900+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
