[2023-05-08T01:45:48.465+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-08T01:45:26.581203+00:00 [queued]>
[2023-05-08T01:45:48.472+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-08T01:45:26.581203+00:00 [queued]>
[2023-05-08T01:45:48.473+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-08T01:45:48.481+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): machine_learning_task> on 2023-05-08 01:45:26.581203+00:00
[2023-05-08T01:45:48.490+0000] {standard_task_runner.py:57} INFO - Started process 582 to run task
[2023-05-08T01:45:48.494+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'machine_learning_task', 'manual__2023-05-08T01:45:26.581203+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp69i5nj_r']
[2023-05-08T01:45:48.497+0000] {standard_task_runner.py:85} INFO - Job 129: Subtask machine_learning_task
[2023-05-08T01:45:48.540+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-08T01:45:26.581203+00:00 [running]> on host d2db9e8a0ded
[2023-05-08T01:45:48.610+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='machine_learning_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T01:45:26.581203+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T01:45:26.581203+00:00'
[2023-05-08T01:45:48.811+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:776: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-05-08T01:45:48.812+0000] {logging_mixin.py:149} INFO - Fitting 3 folds for each of 1 candidates, totalling 3 fits
[2023-05-08T01:45:53.526+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 14s
[2023-05-08T01:45:53.576+0000] {logging_mixin.py:149} INFO - 81/92 [=========================>....] - ETA: 0s 
[2023-05-08T01:45:53.583+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 634us/step
[2023-05-08T01:45:53.599+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=   4.8s
[2023-05-08T01:45:58.500+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 13s
[2023-05-08T01:45:58.550+0000] {logging_mixin.py:149} INFO - 80/92 [=========================>....] - ETA: 0s 
[2023-05-08T01:45:58.557+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 636us/step
[2023-05-08T01:45:58.567+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=   5.0s
[2023-05-08T01:46:03.359+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 13s
[2023-05-08T01:46:03.410+0000] {logging_mixin.py:149} INFO - 83/92 [==========================>...] - ETA: 0s 
[2023-05-08T01:46:03.417+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 637us/step
[2023-05-08T01:46:03.428+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=   4.9s
[2023-05-08T01:46:11.130+0000] {save.py:276} WARNING - Found untraced functions such as _update_step_xla, lstm_cell_3_layer_call_fn, lstm_cell_3_layer_call_and_return_conditional_losses while saving (showing 3 of 3). These functions will not be directly callable after loading.
[2023-05-08T01:46:11.395+0000] {builder_impl.py:798} INFO - Assets written to: /Users/hople/Desktop/Work_sample/model/best_lstm_model.SavedModel/assets
[2023-05-08T01:46:11.555+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-08T01:46:11.566+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=machine_learning_task, execution_date=20230508T014526, start_date=20230508T014548, end_date=20230508T014611
[2023-05-08T01:46:11.806+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-08T01:46:11.836+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
