[2023-05-06T01:19:07.572+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T01:18:44.657268+00:00 [queued]>
[2023-05-06T01:19:07.580+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T01:18:44.657268+00:00 [queued]>
[2023-05-06T01:19:07.581+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-06T01:19:07.590+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): machine_learning_task> on 2023-05-06 01:18:44.657268+00:00
[2023-05-06T01:19:07.600+0000] {standard_task_runner.py:57} INFO - Started process 470 to run task
[2023-05-06T01:19:07.605+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'machine_learning_task', 'manual__2023-05-06T01:18:44.657268+00:00', '--job-id', '762', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpyos2y29k']
[2023-05-06T01:19:07.606+0000] {standard_task_runner.py:85} INFO - Job 762: Subtask machine_learning_task
[2023-05-06T01:19:07.653+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T01:18:44.657268+00:00 [running]> on host 342878f2debe
[2023-05-06T01:19:07.726+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='machine_learning_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-06T01:18:44.657268+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-06T01:18:44.657268+00:00'
[2023-05-06T01:19:07.816+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/fetching_best_model.py", line 34, in best_model_search
    joblib.dump(scaler, '/Users/hople/Desktop/Work_sample/dags/saved_model/scaler.save')
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 552, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/dags/saved_model/scaler.save'
[2023-05-06T01:19:07.827+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=machine_learning_task, execution_date=20230506T011844, start_date=20230506T011907, end_date=20230506T011907
[2023-05-06T01:19:07.838+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 762 for task machine_learning_task ([Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/dags/saved_model/scaler.save'; 470)
[2023-05-06T01:19:07.898+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-06T01:19:07.913+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
