[2023-05-03T07:33:55.937+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.data_processing_task_3 manual__2023-05-03T07:33:53.541330+00:00 [queued]>
[2023-05-03T07:33:55.965+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.data_processing_task_3 manual__2023-05-03T07:33:53.541330+00:00 [queued]>
[2023-05-03T07:33:55.967+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T07:33:55.969+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-05-03T07:33:55.971+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-05-03T07:33:56.008+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): data_processing_task_3> on 2023-05-03 07:33:53.541330+00:00
[2023-05-03T07:33:56.025+0000] {standard_task_runner.py:55} INFO - Started process 31486 to run task
[2023-05-03T07:33:56.044+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'data_processing_task_3', 'manual__2023-05-03T07:33:53.541330+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpiq8fmwbb']
[2023-05-03T07:33:56.050+0000] {standard_task_runner.py:83} INFO - Job 63: Subtask data_processing_task_3
[2023-05-03T07:33:56.265+0000] {task_command.py:389} INFO - Running <TaskInstance: ml_pipeline.data_processing_task_3 manual__2023-05-03T07:33:53.541330+00:00 [running]> on host 46ed3ffab080
[2023-05-03T07:33:57.602+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=lequanghop844@gmail.com
AIRFLOW_CTX_DAG_OWNER=Felix Le
AIRFLOW_CTX_DAG_ID=ml_pipeline
AIRFLOW_CTX_TASK_ID=data_processing_task_3
AIRFLOW_CTX_EXECUTION_DATE=2023-05-03T07:33:53.541330+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-03T07:33:53.541330+00:00
[2023-05-03T07:36:14.343+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/data_processing.py", line 18, in data_processing
    temp = list(map(add_name, preprocessing_list[batch_number]))
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 23, in add_name
    save_parquet(df[features], name, path)
  File "/opt/airflow/dags/utils/save_parquet.py", line 7, in save_parquet
    df_stock.to_parquet(path+stock_name+'.parquet', engine = 'pyarrow', compression = 'gzip')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 2685, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 423, in to_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 180, in write
    is_dir=partition_cols is not None,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 102, in _get_path_or_handle
    path_or_handle, mode, is_text=False, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/data/processed_stocks_etfs/REZI.parquet'
[2023-05-03T07:36:14.489+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=data_processing_task_3, execution_date=20230503T073353, start_date=20230503T073355, end_date=20230503T073614
[2023-05-03T07:36:14.782+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 63 for task data_processing_task_3 ([Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/data/processed_stocks_etfs/REZI.parquet'; 31486)
[2023-05-03T07:36:15.671+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-03T07:36:17.139+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
